language: cpp
dist: trusty
sudo: required

git:
    submodules: false

env:
  global:
  - HEADLESS=True
  matrix:
  - CONFIG=Debug
  #  - CONFIG=Release

matrix:
  include:
  - os: osx
    env:
    - BUILDSCRIPT=osx
  - os: linux
    env:
    - BUILDSCRIPT=linux-static

addons:
  homebrew:
    packages:
    - qt5
    - protobuf
    - openssl
    update: true
  apt:
    packages:
    - libssl-dev
    - libprotobuf-dev
    - protobuf-compiler
    - qt5-qmake
    - qt5-default
    - qtbase5-dev
    - qttools5-dev-tools
    - qtdeclarative5-dev

install:
  - set +x
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export PATH="$(brew --prefix qt5)/bin:$PATH"
      export OPENSSLDIR="$(brew --prefix openssl)"
      ;
    fi

script:
  - cd buildscripts
  - "${BUILDSCRIPT}/test.sh"

after_success:
  - "${BUILDSCRIPT}/build.sh"
