language: cpp
dist: trusty
sudo: required
git:
  submodules: false
env:
  global:
  - HEADLESS=True
  matrix:
  - CONFIG=Debug
matrix:
  include:
  - os: osx
    env:
    - BUILDSCRIPT=osx
  - os: linux
    env:
    - BUILDSCRIPT=linux-static
addons:
  homebrew:
    packages:
    - qt5
    - protobuf
    - openssl
    - tor
    update: true
  apt:
    packages:
    - libssl-dev
    - libprotobuf-dev
    - protobuf-compiler
    - qt5-qmake
    - qt5-default
    - qtbase5-dev
    - qttools5-dev-tools
    - qtdeclarative5-dev
    - xvfb
    - libxrender1
    - tor
install:
- set -x
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    export PATH="$(brew --prefix qt5)/bin:$PATH";
    export OPENSSLDIR="$(brew --prefix openssl)";
  fi
- mkdir -p "buildscripts/output"
- cp "$(which tor)" "buildscripts/output/tor"
script:
- pushd buildscripts
- "${BUILDSCRIPT}/test.sh"
- "${BUILDSCRIPT}/build.sh"
- popd
deploy:
  provider: releases
  api_key:
    secure: lIHMpIYSRcQAzFnbKeucjndUCzCVH78CZ7JpgB7BpUSO/F61ngdW9oWy8oJWdMb1JU0efSRRYNXbX4lTVBOS/iueqfoL6jNojT7t8yVgM31ZfnzJipqdtUHBDHHUHDEQez7MXudUpa9Zo6yCoHF8IT30NiKErbi7jG5YIEaxYzMR2ICWSkechFbGwe6nFgVW8iceNBW8GyyeBpkII7arTpJbZZlrcWDh+Ej5r6fHivV7oifuhSZ6VUYT3dB0tOqcHPU8OtnFpq1sQOtNwr+KNBEfBGLd+gyCXTdjmUebBXnSI6nR3hKEEQR87znlqFrzYKq2OwXqtYkTtc7MpSbmzH9bfxqC4WUa/8QL77cgLJWzhAaOe6+nqeadEJFEFB31KLOlt2SbsMyBy2xWi+NS43VOVz6FecbhgODq7QpXBN5kvN6kjc5kc7xY8joQW5k939/kN5P4DfpePd//bvmUzCVdYaak2pPKLzsyY5dXGqk7z3lGVE3h5Q+8EOnbsEvSrbhNF+Svm/FAEbjUMnaAx20o66MxPxvbb+I0iNT72+jqJypZLv5mjkw2ItMJR1G5zD95qxgZakzJ3liSSpGROBzpLSGQb8GQpOktY9UzocIM0pqyawg2Hfn6y1D9Ptp1SfOZ8rFJvqI+Mxv3FFp+lD3tOV6MvFj1+EJ8PiHyIQc=
  skip_cleanup: true
  file_glob: true
  file:
  - 'buildscripts/output/Ricochet-Refresh-*.dmg'
  - 'buildscripts/output/ricochet-refresh-*-static.tar.bz2'
  on:
    repo: blueprint-freespeech/ricochet-refresh
    tags: true
  overwrite: true
  draft: true
