language: cpp
dist: trusty
sudo: required

git:
    submodules: false

env:
  - CONFIG=Debug
    #  - CONFIG=Release

matrix:
  include:
  - os: osx
    env:
    - BUILDSCRIPT=osx
  - os: linux
    enc:
    - BUILDSCRIPT=linux-static

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
         sudo apt-get install -qq libssl-dev libprotobuf-dev protobuf-compiler
      && sudo apt-get install -qq qt5-qmake qt5-default qtbase5-dev qttools5-dev-tools qtdeclarative5-dev
      ;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
         brew install qt5
      && brew install protobuf
      && brew install openssl
      export PATH="$(brew --prefix qt5)/bin:$PATH"
      ;
    fi

script:
  - cd buildscripts
  - "${BUILDSCRIPT}/test.sh"

after_success:
  - "${BUILDSCRIPT}/build.sh"
